lenses do not work :
[IJ]sbt:IM root project> compile
[error] /Users/joco/dev/im/irie/layer_V_JS_client/src/main/scala/app/client/ui/components/router/mainPageComp/cacheTestMPC/AddTheThieveryNumbersUsingTheServer.scala:23:14: macro annotation could not be expanded (the most common reason for that is that you need to enable the macro paradise plugin; another possibility is that you try to use macro annotation in the same compilation run that defines it)
[error]   case class OurState(tn: TheThieveryNumber, sumIntViewPars: SumIntView_Par )
[error]              ^
[error] one error found
[error] (layer_V_JS_client / Compile / compileIncremental) Compilation failed
[error] Total time: 33 s, completed Jul 14, 2019 7:35:26 AM
[IJ]sbt:IM root project>

We try now with deeper cleaning.